# Generated by Django 5.1.6 on 2025-03-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0006_alter_estimate_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='측정 주소'),
        ),
    ]
