# Generated by Django 5.1.6 on 2025-03-07 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0009_remove_estimate_service_category_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='service_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_estimates', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='service_categories',
            field=models.ManyToManyField(related_name='estimates', to='services.servicecategory'),
        ),
    ]
