# Generated by Django 5.1.6 on 2025-03-10 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0010_estimate_service_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedEstimate',
            fields=[
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='received_estimate', serialize=False, to='estimates.estimate')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='수신 일시')),
            ],
            options={
                'verbose_name': '받은 견적',
                'verbose_name_plural': '받은 견적 목록',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='estimate',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_estimates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimate',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
    ]
