# Generated by Django 5.1.6 on 2025-02-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_servicecategory_remove_customuser_attachment_and_more'),
    ]

    operations = [
    ]
