# Generated by Django 5.1.6 on 2025-03-13 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_provideruser_business_registration_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_request_id', models.IntegerField(help_text='공통 API의 견적 요청 ID')),
                ('maintain_points', models.IntegerField(default=0)),
                ('recommend_points', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', '임시저장'), ('SENT', '발송됨'), ('ACCEPTED', '수락됨'), ('REJECTED', '거절됨')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_estimates',
                'ordering': ['-created_at'],
            },
        ),
    ]
