# Generated by Django 5.1.6 on 2025-03-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_providerestimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerestimate',
            name='measurement_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='providerestimate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='providerestimate',
            name='status',
            field=models.CharField(choices=[('DRAFT', '임시저장'), ('SAVED', '저장됨'), ('SENT', '발송됨'), ('ACCEPTED', '수락됨'), ('REJECTED', '거절됨')], default='DRAFT', max_length=20),
        ),
    ]
