# Generated by Django 5.1.6 on 2025-02-19 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_initial_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': '서비스 카테고리', 'verbose_name_plural': '서비스 카테고리'},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='category_code',
            field=models.CharField(choices=[('indoor-air', '실내공기질'), ('noise-vibration', '소음·진동'), ('odor', '악취'), ('water', '수질'), ('air', '대기'), ('major-disaster', '중대재해'), ('office', '사무실'), ('esg', 'ESG경영'), ('etc', '기타')], default=django.utils.timezone.now, max_length=20, unique=True, verbose_name='카테고리 코드'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='service_category',
            field=models.ManyToManyField(related_name='providers', to='users.servicecategory', verbose_name='분야'),
        ),
    ]
