# Generated by Django 5.1.6 on 2025-03-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_providerestimate_measurement_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerestimate',
            name='measurement_manager',
        ),
        migrations.AddField(
            model_name='providerestimate',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerestimate',
            name='writer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='providerestimate',
            name='writer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='providerestimate',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='providerestimate',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
