# Generated by Django 5.1.6 on 2025-03-03 05:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='결제 식별자')),
                ('estimate_id', models.IntegerField(default=0, verbose_name='견적 id')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='결제 금액')),
                ('payment_method', models.CharField(choices=[('card', '카드'), ('bank_transfer', '계좌이체'), ('virtual_account', '가상계좌'), ('other', '기타')], max_length=20, verbose_name='결제방법')),
                ('is_paid', models.BooleanField(default=False, verbose_name='결제 여부')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제 완료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='부가세')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 결제금액')),
                ('status', models.CharField(choices=[('PENDING', '결제대기'), ('PROCESSING', '처리중'), ('COMPLETED', '결제완료'), ('FAILED', '결제실패'), ('CANCELLED', '결제취소'), ('REFUNDED', '환불완료')], default='PENDING', max_length=20, verbose_name='결제상태')),
                ('pg_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='PG사 거래번호')),
                ('payment_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='결제 키')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제 목록',
                'db_table': 'payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(max_length=20, unique=True, verbose_name='환불번호')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='환불금액')),
                ('reason', models.TextField(verbose_name='환불사유')),
                ('status', models.CharField(choices=[('PENDING', '환불대기'), ('PROCESSING', '처리중'), ('COMPLETED', '환불완료'), ('FAILED', '환불실패')], default='PENDING', max_length=20, verbose_name='환불상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='환불완료일시')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payment.payment', verbose_name='결제')),
            ],
            options={
                'verbose_name': '환불',
                'verbose_name_plural': '환불 목록',
                'db_table': 'payment_refunds',
                'ordering': ['-created_at'],
            },
        ),
    ]
