# Generated by Django 5.1.6 on 2025-03-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(choices=[('indoor-air', '실내공기질'), ('noise-vibration', '소음·진동'), ('odor', '악취'), ('water', '수질'), ('air', '대기'), ('major-disaster', '중대재해'), ('office', '사무실'), ('esg', 'ESG경영'), ('etc', '기타')], max_length=50, unique=True, verbose_name='카테고리 코드')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='서비스 카테고리명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '측정 종류',
                'verbose_name_plural': '서비스 카테고리 목록',
            },
        ),
    ]
