# Generated by Django 5.1.6 on 2025-03-05 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_servicecategory_alter_adminuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='demand_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='users.demanduser', verbose_name='수요업체 사용자'),
        ),
        migrations.AddField(
            model_name='company',
            name='provider_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='users.provideruser', verbose_name='대행사 사용자'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending', '승인대기'), ('approved', '승인완료')], max_length=20),
        ),
    ]
