# Generated by Django 5.1.6 on 2025-02-20 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 사용일')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 상태')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to='authtoken.token', verbose_name='토큰')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'API 토큰',
                'verbose_name_plural': 'API 토큰 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
