# Generated by Django 5.1.6 on 2025-02-20 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanelToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='관리자 토큰')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 사용일')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 상태')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_tokens', to=settings.AUTH_USER_MODEL, verbose_name='관리자')),
            ],
            options={
                'verbose_name': '관리자 패널 토큰',
                'verbose_name_plural': '관리자 패널 토큰 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
